workflows:
  workflow-name:
    name: Android Build Workflow # 워크플로우 이름 (원하는 이름으로 변경 가능)
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - |
        set -e
        flutter pub get
        flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - ossangworld@gmail.com
